defmodule Gofitback.Repo.Migrations.CreateCheckinAndUserHistoricRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_historic) do
      add :checkin_id,
          references(:checkins,
            column: :id,
            name: "user_historic_checkin_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:user_historic, "user_historic_checkin_id_fkey")

    alter table(:user_historic) do
      remove :checkin_id
    end
  end
end
