defmodule Gofitback.Repo.Migrations.AlterUserResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:users) do
      remove :confirmed_at
      add :name, :text, null: false
      add :active, :boolean, null: false, default: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:users) do
      remove :updated_at
      remove :created_at
      remove :active
      remove :name
      add :confirmed_at, :utc_datetime_usec
    end
  end
end
