defmodule Gofitback.Repo.Migrations.CreateTablesUserHistoricAndGameType do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_historic, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :points, :bigint, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :update_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_historic_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :game_type_id, :uuid
    end

    create table(:game_type, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:user_historic) do
      modify :game_type_id,
             references(:game_type,
               column: :id,
               name: "user_historic_game_type_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:game_type) do
      add :name, :text, null: false
      add :description, :text, null: false
      add :weight, :bigint, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :update_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:game_type) do
      remove :update_at
      remove :created_at
      remove :weight
      remove :description
      remove :name
    end

    drop constraint(:user_historic, "user_historic_game_type_id_fkey")

    alter table(:user_historic) do
      modify :game_type_id, :uuid
    end

    drop table(:game_type)

    drop constraint(:user_historic, "user_historic_user_id_fkey")

    drop table(:user_historic)
  end
end
