defmodule Gofitback.Repo.Migrations.CreateCheckinResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:checkins, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :day, :date, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "checkins_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create index(:checkins, [:user_id, :day], unique: true)

    create unique_index(:checkins, [:user_id, :day],
             name: "checkins_unique_user_checkin_per_day_index"
           )
  end

  def down do
    drop_if_exists unique_index(:checkins, [:user_id, :day],
                     name: "checkins_unique_user_checkin_per_day_index"
                   )

    drop constraint(:checkins, "checkins_user_id_fkey")

    drop_if_exists index(:checkins, [:user_id, :day])

    drop table(:checkins)
  end
end
